/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { STORE_SELECTION_GUIDANCE } from './store-selection.js';

export function getArchiveChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-archive-change',
    description: 'Archive a completed change in the experimental workflow. Use when the user wants to finalize and archive a change after implementation is complete.',
    instructions: `Archive a completed change in the experimental workflow.

${STORE_SELECTION_GUIDANCE}

**Input**: Optionally specify a change name. If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **If no change name provided, prompt for selection**

   Run \`openspec list --json\` to get available changes. Use the **AskUserQuestion tool** to let the user select.

   Show only active changes (not already archived).
   Include the schema used for each change if available.

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

2. **Check artifact completion status**

   Run \`openspec status --change "<name>" --json\` to check artifact completion.

   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used
   - \`planningHome\`, \`changeRoot\`, \`artifactPaths\`, and \`actionContext\`: path and scope context
   - \`artifacts\`: List of artifacts with their status (\`done\` or other)

   **If any artifacts are not \`done\`:**
   - Display warning listing incomplete artifacts
   - Use **AskUserQuestion tool** to confirm user wants to proceed
   - Proceed if user confirms

3. **Check task completion status**

   Read the tasks file (typically \`tasks.md\`) to check for incomplete tasks.

   Count tasks marked with \`- [ ]\` (incomplete) vs \`- [x]\` (complete).

   **If incomplete tasks found:**
   - Display warning showing count of incomplete tasks
   - Use **AskUserQuestion tool** to confirm user wants to proceed
   - Proceed if user confirms

   **If no tasks file exists:** Proceed without task-related warning.

4. **Propose verification (if implementation appears complete)**

   Run this check only when tasks are all complete (or no tasks file) AND delta specs exist.
   Skip silently if either condition is not met.

   Use the **AskUserQuestion tool** to ask:
   > "All tasks are complete. Would you like to verify that the implementation matches the specs before archiving? This catches any drift between what was built and what was specced."

   Options: "Yes, run verify first" (recommended), "No, skip verify"

   **If user chooses verify:**
   Invoke the verify skill using the Task tool:
   \`\`\`
   subagent_type: "general-purpose"
   prompt: "Use Skill tool to invoke openspec-verify-change for change '<name>'. The user is about to archive and wants to confirm implementation matches specs."
   \`\`\`
   After verify completes, show the verify summary and ask: "Verify complete. Proceed with archive?"
   - If user confirms: continue
   - If user cancels: stop and let them fix issues first

   **If user skips verify:** Continue to next step.

5. **Perform the archive**

   Run the archive CLI command. It applies delta specs to \`openspec/specs/\`, patches \`openspec/arch/\`, and moves the change to archive — all atomically:
   \`\`\`bash
   openspec archive "<name>" --yes
   \`\`\`

   The \`--yes\` flag confirms any remaining prompts (incomplete task warnings, spec update confirmation).
   All prior confirmations (steps 2–4) have already been collected.

   **If the command fails:** Show the full error output and stop. Do not attempt manual recovery.

6. **Display summary**

   Show archive completion summary combining verify status (from step 4) and CLI output:
   - Change name
   - Schema that was used
   - Archive location (from CLI output)
   - Verify status (passed / skipped)
   - Spec sync result (from CLI output: specs updated / no delta specs)
   - Arch patch result (from CLI output: layers patched / no arch folder)
   - Note about any warnings (incomplete artifacts/tasks)

**Output On Success**

\`\`\`
## Archive Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** changes/archive/YYYY-MM-DD-<name>/
**Verify:** ✓ Passed
**Specs:** ✓ Synced to main specs
**Arch:** ✓ Patched

All artifacts complete. All tasks complete.
\`\`\`

**Output On Success (Verify Skipped)**

\`\`\`
## Archive Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** changes/archive/YYYY-MM-DD-<name>/
**Verify:** Skipped
**Specs:** ✓ Synced to main specs (or "No delta specs")
**Arch:** ✓ Patched (or "No arch folder")

All artifacts complete. All tasks complete.
\`\`\`

**Guardrails**
- Always prompt for change selection if not provided
- Use artifact graph (openspec status --json) for completion checking
- Don't block archive on warnings - just inform and confirm
- Always use \`openspec archive <name> --yes\` — never use manual \`mv\` or \`mkdir\`; the CLI is the only way specs and arch get applied to the main folders
- Only propose verify when tasks are all complete AND delta specs exist — skip the prompt otherwise`,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxArchiveCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Archive',
    description: 'Archive a completed change in the experimental workflow',
    category: 'Workflow',
    tags: ['workflow', 'archive', 'experimental'],
    content: `Archive a completed change in the experimental workflow.

${STORE_SELECTION_GUIDANCE}

**Input**: Optionally specify a change name after \`/opsx:archive\` (e.g., \`/opsx:archive add-auth\`). If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **If no change name provided, prompt for selection**

   Run \`openspec list --json\` to get available changes. Use the **AskUserQuestion tool** to let the user select.

   Show only active changes (not already archived).
   Include the schema used for each change if available.

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

2. **Check artifact completion status**

   Run \`openspec status --change "<name>" --json\` to check artifact completion.

   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used
   - \`planningHome\`, \`changeRoot\`, \`artifactPaths\`, and \`actionContext\`: path and scope context
   - \`artifacts\`: List of artifacts with their status (\`done\` or other)

   **If any artifacts are not \`done\`:**
   - Display warning listing incomplete artifacts
   - Prompt user for confirmation to continue
   - Proceed if user confirms

3. **Check task completion status**

   Read the tasks file (typically \`tasks.md\`) to check for incomplete tasks.

   Count tasks marked with \`- [ ]\` (incomplete) vs \`- [x]\` (complete).

   **If incomplete tasks found:**
   - Display warning showing count of incomplete tasks
   - Prompt user for confirmation to continue
   - Proceed if user confirms

   **If no tasks file exists:** Proceed without task-related warning.

4. **Propose verification (if implementation appears complete)**

   Run this check only when tasks are all complete (or no tasks file) AND delta specs exist.
   Skip silently if either condition is not met.

   Use the **AskUserQuestion tool** to ask:
   > "All tasks are complete. Would you like to verify that the implementation matches the specs before archiving? This catches any drift between what was built and what was specced."

   Options: "Yes, run verify first" (recommended), "No, skip verify"

   **If user chooses verify:**
   Invoke the verify skill using the Task tool:
   \`\`\`
   subagent_type: "general-purpose"
   prompt: "Use Skill tool to invoke openspec-verify-change for change '<name>'. The user is about to archive and wants to confirm implementation matches specs."
   \`\`\`
   After verify completes, show the verify summary and ask: "Verify complete. Proceed with archive?"
   - If user confirms: continue
   - If user cancels: stop and let them fix issues first

   **If user skips verify:** Continue to next step.

5. **Perform the archive**

   Run the archive CLI command. It applies delta specs to \`openspec/specs/\`, patches \`openspec/arch/\`, and moves the change to archive — all atomically:
   \`\`\`bash
   openspec archive "<name>" --yes
   \`\`\`

   The \`--yes\` flag confirms any remaining prompts (incomplete task warnings, spec update confirmation).
   All prior confirmations (steps 2–4) have already been collected.

   **If the command fails:** Show the full error output and stop. Do not attempt manual recovery.

6. **Display summary**

   Show archive completion summary combining verify status (from step 4) and CLI output:
   - Change name
   - Schema that was used
   - Archive location (from CLI output)
   - Verify status (passed / skipped)
   - Spec sync result (from CLI output: specs updated / no delta specs)
   - Arch patch result (from CLI output: layers patched / no arch folder)
   - Note about any warnings (incomplete artifacts/tasks)

**Output On Success**

\`\`\`
## Archive Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** changes/archive/YYYY-MM-DD-<name>/
**Verify:** ✓ Passed
**Specs:** ✓ Synced to main specs
**Arch:** ✓ Patched

All artifacts complete. All tasks complete.
\`\`\`

**Output On Success (Verify Skipped)**

\`\`\`
## Archive Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** changes/archive/YYYY-MM-DD-<name>/
**Verify:** Skipped
**Specs:** ✓ Synced to main specs (or "No delta specs")
**Arch:** ✓ Patched (or "No arch folder")

All artifacts complete. All tasks complete.
\`\`\`

**Output On Success With Warnings**

\`\`\`
## Archive Complete (with warnings)

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** changes/archive/YYYY-MM-DD-<name>/
**Verify:** Skipped
**Specs:** ✓ Synced to main specs
**Arch:** No arch folder

**Warnings:**
- Archived with 2 incomplete artifacts
- Archived with 3 incomplete tasks

Review the archive if this was not intentional.
\`\`\`

**Output On Error (Archive Exists)**

\`\`\`
## Archive Failed

**Change:** <change-name>
**Error:** openspec archive reported: Target archive already exists

**Options:**
1. Rename the existing archive manually, then retry
2. Wait until a different date to archive
\`\`\`

**Guardrails**
- Always prompt for change selection if not provided
- Use artifact graph (openspec status --json) for completion checking
- Don't block archive on warnings - just inform and confirm
- Always use \`openspec archive <name> --yes\` — never use manual \`mv\` or \`mkdir\`; the CLI is the only way specs and arch get applied to the main folders
- Only propose verify when tasks are all complete AND delta specs exist — skip the prompt otherwise`
  };
}
